### ISSUE TITLE
"Sort members" unavailable in visual studio 2022

### ISSUE THREAD

**Issue by Silex** [menees/VsTools#5]
Cannot find the sort menu, even when pressing shift.

My version is `Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.3.5`

**Comment by Silex** [comment]
Ah, found that you have to select text before accessing the menu!

**Comment by Aquapisces** [comment]
I tried by selecting the text firts, but only "sort lines" became visible... I'm using it on C++, what about u, bro?

**Comment by menees** [comment]
"Sort Members" only supports C# and VB because it depends on Microsoft's [FileCodeModel2](https://learn.microsoft.com/en-us/dotnet/api/envdte80.filecodemodel2?view=visualstudiosdk-2022) interface to find and select the members. Microsoft only provides a FileCodeModel2 implementation for C# and VB not C++.
